server:
  port:8081
sender:
  base:
    url:http://localhost:8082

#logging level
logging:
  level:
    root=INFO
  pattern:
    console:{\"%p\",\"%thread\",\"%logger{0}\",\"%replace(%m%ex){'[\r\n]+', '\\n'}%nopex\"}%n
#micrometer
management:
  metrics:
    export:
      prometheus:
        enabled:false
  tags:
    app:address-book-invoker
  endpoint:
    metrics:
      enabled:true
  endpoints:
    web:
      exposure:
        include:*
