server:
  port: 8083
#logging
logging:
  level:
    root:INFO
  pattern:
    console:{\"%p\",\"%thread\",\"%logger{0}\",\"%replace(%m%ex){'[\r\n]+', '\\n'}%nopex\"}%n
#micrometer
management:
  metrics:
    export:
    prometheus:
    enabled:false
  tags:
    app:address-book-receiver
  endpoint:
    metrics:
    enabled:true
    web:
    exposure:
    include:*
kafka:
  boot:
    server: localhost:9092
  topic:
    name: address-sender
  consumer:
    group:
      id: myTopic-group-id