server:
  port: 8083

# Kafka
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group: address-book
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topic:
      name: address

#micrometer
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: false
    tags:
      app: address-book-invoker

#logging level
logging:
  level:
    root: INFO
  pattern:
    console: "{\"%p\",\"%thread\",\"%logger{0}\",\"%replace(%m%ex){'[\r\n]+', '\\n'}%nopex\"}%n"
